xth.product.version=${project.version}
xth.product.description=Test harness for running the W3C XPath, XQuery, and XSLT tests
xth.product.copyright=Copyright (C) ${project.inceptionYear}, ${project.organization.name}
default.qt.git.repo.uri=https://github.com/w3c/qt3tests.git
default.qt.git.branch=master
default.cache.directory-name=xth
default.output.directory-name=results